luma.ai.api-key=luma-6fb387f2-1fdc-4268-a3fb-b8b48aa00f32-b16fa178-eb6a-4cec-a611-89750fbd9624
luma.ai.base-url=https://api.lumalabs.ai/dream-machine/v1/generations

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# Enable task scheduling (default is enabled in Spring Boot)
spring.task.scheduling.pool.size=5